language: ruby
  
script:
  - bundle exec rspec
  - bundle exec rake install
  
install: bundle install --without debugger

rvm:
#  - 2.2.x or earlier cannot run because mediawiki-butt requires at least Ruby 2.3
  - 2.3.4
  - 2.4.1
  - 2.5.0

matrix:
  allow_failures:
    - rvm: 2.3.4

notifications:
  email:
    recipients:
      - niklaus.giger@member.fsf.org

